# -*- coding: utf-8 -*-
"""Pix2Pix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpCFZrm7Y63bBFTTpx6F6lhwbx_ZU4xB
"""

# ==============================
# INSTALL DEPENDENCIES
# ==============================

!pip install -q tensorflow matplotlib

# ==============================
# IMPORT LIBRARIES
# ==============================

import tensorflow as tf
import os
import time
import numpy as np
import matplotlib.pyplot as plt

from IPython import display
from tensorflow.keras import layers

print("TensorFlow Version:", tf.__version__)

# ==============================
# DOWNLOAD FACADES DATASET
# ==============================

dataset_url = "http://efrosgans.eecs.berkeley.edu/pix2pix/datasets/facades.tar.gz"

path_to_zip = tf.keras.utils.get_file(
    'facades.tar.gz',
    origin=dataset_url,
    extract=True
)

PATH = os.path.join(os.path.dirname(path_to_zip), 'facades')

print(PATH)

# ==============================
# PARAMETERS
# ==============================

BUFFER_SIZE = 400
BATCH_SIZE = 1
IMG_WIDTH = 256
IMG_HEIGHT = 256
LAMBDA = 100

# ==============================
# LOAD IMAGE
# ==============================

def load(image_file):

    image = tf.io.read_file(image_file)
    image = tf.io.decode_jpeg(image)

    w = tf.shape(image)[1]
    w = w // 2

    input_image = image[:, w:, :]
    real_image = image[:, :w, :]

    input_image = tf.cast(input_image, tf.float32)
    real_image = tf.cast(real_image, tf.float32)

    return input_image, real_image


# ==============================
# RESIZE
# ==============================

def resize(input_image, real_image, height, width):

    input_image = tf.image.resize(
        input_image,
        [height, width],
        method=tf.image.ResizeMethod.NEAREST_NEIGHBOR
    )

    real_image = tf.image.resize(
        real_image,
        [height, width],
        method=tf.image.ResizeMethod.NEAREST_NEIGHBOR
    )

    return input_image, real_image


# ==============================
# RANDOM CROP
# ==============================

def random_crop(input_image, real_image):

    stacked_image = tf.stack([input_image, real_image], axis=0)

    cropped_image = tf.image.random_crop(
        stacked_image,
        size=[2, IMG_HEIGHT, IMG_WIDTH, 3]
    )

    return cropped_image[0], cropped_image[1]


# ==============================
# NORMALIZE
# ==============================

def normalize(input_image, real_image):

    input_image = (input_image / 127.5) - 1
    real_image = (real_image / 127.5) - 1

    return input_image, real_image


# ==============================
# RANDOM JITTER
# ==============================

@tf.function()
def random_jitter(input_image, real_image):

    input_image, real_image = resize(
        input_image,
        real_image,
        286,
        286
    )

    input_image, real_image = random_crop(
        input_image,
        real_image
    )

    if tf.random.uniform(()) > 0.5:

        input_image = tf.image.flip_left_right(input_image)
        real_image = tf.image.flip_left_right(real_image)

    return input_image, real_image

# ==============================
# TRAIN IMAGE LOADER
# ==============================

def load_image_train(image_file):

    input_image, real_image = load(image_file)

    input_image, real_image = random_jitter(
        input_image,
        real_image
    )

    input_image, real_image = normalize(
        input_image,
        real_image
    )

    return input_image, real_image


# ==============================
# TEST IMAGE LOADER
# ==============================

def load_image_test(image_file):

    input_image, real_image = load(image_file)

    input_image, real_image = resize(
        input_image,
        real_image,
        IMG_HEIGHT,
        IMG_WIDTH
    )

    input_image, real_image = normalize(
        input_image,
        real_image
    )

    return input_image, real_image

import os

# ==============================
# TRAIN DATASET
# ==============================

# Correctly define PATH to point to the root of the extracted 'facades' dataset.
# The 'path_to_zip' variable points to the directory where the archive was extracted,
# and the actual dataset is within a 'facades' subdirectory there.
PATH = os.path.join(path_to_zip, 'facades')


train_dataset = tf.data.Dataset.list_files(
    PATH + '/train/*.jpg'
)

train_dataset = train_dataset.map(
    load_image_train,
    num_parallel_calls=tf.data.AUTOTUNE
)

train_dataset = train_dataset.shuffle(BUFFER_SIZE)

train_dataset = train_dataset.batch(BATCH_SIZE)


# ==============================
# TEST DATASET
# ==============================

test_dataset = tf.data.Dataset.list_files(
    PATH + '/test/*.jpg'
)

test_dataset = test_dataset.map(load_image_test)

test_dataset = test_dataset.batch(BATCH_SIZE)

# ==============================
# DISPLAY SAMPLE IMAGES
# ==============================

for input_image, real_image in train_dataset.take(1):

    plt.figure(figsize=(10, 10))

    display_list = [input_image[0], real_image[0]]
    title = ['Input Image', 'Ground Truth']

    for i in range(2):

        plt.subplot(1, 2, i + 1)
        plt.title(title[i])

        plt.imshow(display_list[i] * 0.5 + 0.5)

        plt.axis('off')

    plt.show()

# ==============================
# DOWNSAMPLER
# ==============================

def downsample(filters, size, apply_batchnorm=True):

    initializer = tf.random_normal_initializer(0., 0.02)

    result = tf.keras.Sequential()

    result.add(
        layers.Conv2D(
            filters,
            size,
            strides=2,
            padding='same',
            kernel_initializer=initializer,
            use_bias=False
        )
    )

    if apply_batchnorm:
        result.add(layers.BatchNormalization())

    result.add(layers.LeakyReLU())

    return result


# ==============================
# UPSAMPLER
# ==============================

def upsample(filters, size, apply_dropout=False):

    initializer = tf.random_normal_initializer(0., 0.02)

    result = tf.keras.Sequential()

    result.add(
        layers.Conv2DTranspose(
            filters,
            size,
            strides=2,
            padding='same',
            kernel_initializer=initializer,
            use_bias=False
        )
    )

    result.add(layers.BatchNormalization())

    if apply_dropout:
        result.add(layers.Dropout(0.5))

    result.add(layers.ReLU())

    return result

# ==============================
# GENERATOR
# ==============================

def Generator():

    inputs = layers.Input(shape=[256, 256, 3])

    down_stack = [

        downsample(64, 4, apply_batchnorm=False),
        downsample(128, 4),
        downsample(256, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
    ]

    up_stack = [

        upsample(512, 4, apply_dropout=True),
        upsample(512, 4, apply_dropout=True),
        upsample(512, 4, apply_dropout=True),
        upsample(512, 4),
        upsample(256, 4),
        upsample(128, 4),
        upsample(64, 4),
    ]

    initializer = tf.random_normal_initializer(0., 0.02)

    last = layers.Conv2DTranspose(
        3,
        4,
        strides=2,
        padding='same',
        kernel_initializer=initializer,
        activation='tanh'
    )

    x = inputs

    skips = []

    for down in down_stack:
        x = down(x)
        skips.append(x)

    skips = reversed(skips[:-1])

    for up, skip in zip(up_stack, skips):

        x = up(x)
        x = layers.Concatenate()([x, skip])

    x = last(x)

    return tf.keras.Model(inputs=inputs, outputs=x)


generator = Generator()

generator.summary()

# ==============================
# DISCRIMINATOR
# ==============================

def Discriminator():

    initializer = tf.random_normal_initializer(0., 0.02)

    inp = layers.Input(shape=[256, 256, 3], name='input_image')

    tar = layers.Input(shape=[256, 256, 3], name='target_image')

    x = layers.concatenate([inp, tar])

    down1 = downsample(64, 4, False)(x)
    down2 = downsample(128, 4)(down1)
    down3 = downsample(256, 4)(down2)

    zero_pad1 = layers.ZeroPadding2D()(down3)

    conv = layers.Conv2D(
        512,
        4,
        strides=1,
        kernel_initializer=initializer,
        use_bias=False
    )(zero_pad1)

    batchnorm1 = layers.BatchNormalization()(conv)

    leaky_relu = layers.LeakyReLU()(batchnorm1)

    zero_pad2 = layers.ZeroPadding2D()(leaky_relu)

    last = layers.Conv2D(
        1,
        4,
        strides=1,
        kernel_initializer=initializer
    )(zero_pad2)

    return tf.keras.Model(inputs=[inp, tar], outputs=last)


discriminator = Discriminator()

discriminator.summary()

# ==============================
# LOSS OBJECT
# ==============================

loss_object = tf.keras.losses.BinaryCrossentropy(
    from_logits=True
)


# ==============================
# GENERATOR LOSS
# ==============================

def generator_loss(disc_generated_output,
                   gen_output,
                   target):

    gan_loss = loss_object(
        tf.ones_like(disc_generated_output),
        disc_generated_output
    )

    l1_loss = tf.reduce_mean(
        tf.abs(target - gen_output)
    )

    total_gen_loss = gan_loss + (LAMBDA * l1_loss)

    return total_gen_loss, gan_loss, l1_loss


# ==============================
# DISCRIMINATOR LOSS
# ==============================

def discriminator_loss(disc_real_output,
                       disc_generated_output):

    real_loss = loss_object(
        tf.ones_like(disc_real_output),
        disc_real_output
    )

    generated_loss = loss_object(
        tf.zeros_like(disc_generated_output),
        disc_generated_output
    )

    total_disc_loss = real_loss + generated_loss

    return total_disc_loss

# ==============================
# OPTIMIZERS
# ==============================

generator_optimizer = tf.keras.optimizers.Adam(
    2e-4,
    beta_1=0.5
)

discriminator_optimizer = tf.keras.optimizers.Adam(
    2e-4,
    beta_1=0.5
)

# ==============================
# GENERATE IMAGES
# ==============================

def generate_images(model, test_input, tar):

    prediction = model(test_input, training=True)

    plt.figure(figsize=(15, 15))

    display_list = [
        test_input[0],
        tar[0],
        prediction[0]
    ]

    title = [
        'Input Image',
        'Ground Truth',
        'Predicted Image'
    ]

    for i in range(3):

        plt.subplot(1, 3, i + 1)

        plt.title(title[i])

        plt.imshow(display_list[i] * 0.5 + 0.5)

        plt.axis('off')

    plt.show()

# ==============================
# TRAIN STEP
# ==============================

@tf.function
def train_step(input_image, target):

    with tf.GradientTape() as gen_tape, \
         tf.GradientTape() as disc_tape:

        gen_output = generator(
            input_image,
            training=True
        )

        disc_real_output = discriminator(
            [input_image, target],
            training=True
        )

        disc_generated_output = discriminator(
            [input_image, gen_output],
            training=True
        )

        gen_total_loss, gen_gan_loss, gen_l1_loss = generator_loss(
            disc_generated_output,
            gen_output,
            target
        )

        disc_loss = discriminator_loss(
            disc_real_output,
            disc_generated_output
        )

    generator_gradients = gen_tape.gradient(
        gen_total_loss,
        generator.trainable_variables
    )

    discriminator_gradients = disc_tape.gradient(
        disc_loss,
        discriminator.trainable_variables
    )

    generator_optimizer.apply_gradients(
        zip(generator_gradients,
            generator.trainable_variables)
    )

    discriminator_optimizer.apply_gradients(
        zip(discriminator_gradients,
            discriminator.trainable_variables)
    )

    return gen_total_loss, disc_loss

# ==============================
# TRAINING LOOP
# ==============================

EPOCHS = 20

for epoch in range(EPOCHS):

    start = time.time()

    print(f"\nEpoch {epoch+1}/{EPOCHS}")

    for n, (input_image, target) in train_dataset.enumerate():

        gen_loss, disc_loss = train_step(
            input_image,
            target
        )

        if n % 100 == 0:
            print(f"Step {n}")

    display.clear_output(wait=True)

    for example_input, example_target in test_dataset.take(1):

        generate_images(
            generator,
            example_input,
            example_target
        )

    print(
        f"Epoch {epoch+1} completed in "
        f"{time.time()-start:.2f} sec"
    )

# ==============================
# SAVE MODEL
# ==============================

generator.save("pix2pix_generator.h5")

print("Generator Model Saved!")

# ==============================
# TEST MODEL
# ==============================

for inp, tar in test_dataset.take(5):

    generate_images(generator, inp, tar)